/* Generated from 'wasm2c.c.tmpl' by wasm2c_tmpl.py, do not edit! */
const char SECTION_NAME(includes)[] =
"#include <assert.h>\n"
"#include <math.h>\n"
"#include <stdlib.h>\n"
"#include <string.h>\n"
"#if _MSC_VER\n"
"#include <xmmintrin.h>\n"
"#include <emmintrin.h>\n"
"#endif\n"
;

const char SECTION_NAME(declarations)[] =
"#if _MSC_VER\n"
"#define UNLIKELY(x) (x)\n"
"#define LIKELY(x) (x)\n"
"#else\n"
"#define UNLIKELY(x) __builtin_expect(!!(x), 0)\n"
"#define LIKELY(x) __builtin_expect(!!(x), 1)\n"
"#endif\n"
"\n"
"#define TRAP(x) (wasm_rt_trap(WASM_RT_TRAP_##x), 0)\n"
"\n"
"#define FUNC_PROLOGUE(frame_size)                                              \\\n"
"  if ((++wasm_rt_call_stack_depth > WASM_RT_MAX_CALL_STACK_DEPTH) ||           \\\n"
"      ((wasm_rt_call_stack_size += frame_size) > WASM_RT_MAX_CALL_STACK_SIZE)) \\\n"
"    TRAP(EXHAUSTION)\n"
"\n"
"#define FUNC_EPILOGUE(frame_size)                                \\\n"
"  --wasm_rt_call_stack_depth;                                    \\\n"
"  wasm_rt_call_stack_size -= frame_size\n"
"\n"
"#define UNREACHABLE TRAP(UNREACHABLE)\n"
"\n"
"#define CALL_INDIRECT(table, t, ft, x, ...)          \\\n"
"  (LIKELY((x) < table.size && table.data[x].func &&  \\\n"
"          table.data[x].func_type == func_types[ft]) \\\n"
"       ? ((t)table.data[x].func)(__VA_ARGS__)        \\\n"
"       : TRAP(CALL_INDIRECT))\n"
"\n"
"#define MEMCHECK(mem, a, t)  \\\n"
"  if (UNLIKELY((a) + sizeof(t) > mem->size)) TRAP(OOB)\n"
"\n"
"#define DEFINE_LOAD(name, t1, t2, t3)                                 \\\n"
"  static inline t3 WASM_RT_CC name(wasm_rt_memory_t* mem, u64 addr) { \\\n"
"    MEMCHECK(mem, addr, t1);                                          \\\n"
"    t1 result;                                                        \\\n"
"    memcpy(&result, &mem->data[addr], sizeof(t1));                    \\\n"
"    return (t3)(t2)result;                                            \\\n"
"  }\n"
"\n"
"#define DEFINE_STORE(name, t1, t2)                                    \\\n"
"  static inline void WASM_RT_CC name(wasm_rt_memory_t* mem, u64 addr, \\\n"
"                                     t2 value) {                      \\\n"
"    MEMCHECK(mem, addr, t1);                                          \\\n"
"    t1 wrapped = (t1)value;                                           \\\n"
"    memcpy(&mem->data[addr], &wrapped, sizeof(t1));                   \\\n"
"  }\n"
"\n"
"DEFINE_LOAD(i32_load, u32, u32, u32);\n"
"DEFINE_LOAD(i64_load, u64, u64, u64);\n"
"DEFINE_LOAD(f32_load, f32, f32, f32);\n"
"DEFINE_LOAD(f64_load, f64, f64, f64);\n"
"DEFINE_LOAD(i32_load8_s, s8, s32, u32);\n"
"DEFINE_LOAD(i64_load8_s, s8, s64, u64);\n"
"DEFINE_LOAD(i32_load8_u, u8, u32, u32);\n"
"DEFINE_LOAD(i64_load8_u, u8, u64, u64);\n"
"DEFINE_LOAD(i32_load16_s, s16, s32, u32);\n"
"DEFINE_LOAD(i64_load16_s, s16, s64, u64);\n"
"DEFINE_LOAD(i32_load16_u, u16, u32, u32);\n"
"DEFINE_LOAD(i64_load16_u, u16, u64, u64);\n"
"DEFINE_LOAD(i64_load32_s, s32, s64, u64);\n"
"DEFINE_LOAD(i64_load32_u, u32, u64, u64);\n"
"DEFINE_STORE(i32_store, u32, u32);\n"
"DEFINE_STORE(i64_store, u64, u64);\n"
"DEFINE_STORE(f32_store, f32, f32);\n"
"DEFINE_STORE(f64_store, f64, f64);\n"
"DEFINE_STORE(i32_store8, u8, u32);\n"
"DEFINE_STORE(i32_store16, u16, u32);\n"
"DEFINE_STORE(i64_store8, u8, u64);\n"
"DEFINE_STORE(i64_store16, u16, u64);\n"
"DEFINE_STORE(i64_store32, u32, u64);\n"
"\n"
"#if _MSC_VER\n"
"#if _M_IX86\n"
"static inline unsigned long LowDword(unsigned __int64 value) {\n"
"  return (unsigned long)value;\n"
"}\n"
"\n"
"static inline unsigned long HighDword(unsigned __int64 value) {\n"
"  unsigned long high;\n"
"  memcpy(&high, (unsigned char*)&value + sizeof(high), sizeof(high));\n"
"  return high;\n"
"}\n"
"#endif\n"
"\n"
"static inline int I32_CLZ(unsigned long mask) {\n"
"  if (mask == 0)\n"
"    return 32;\n"
"  unsigned long index;\n"
"  _BitScanReverse(&index, mask);\n"
"  return sizeof(unsigned long) * 8 - (index + 1);\n"
"}\n"
"\n"
"static inline int I64_CLZ(unsigned __int64 mask) {\n"
"#if _M_X64\n"
"  if (mask == 0) return 64;\n"
"  unsigned long index;\n"
"  _BitScanReverse64(&index, mask);\n"
"  return sizeof(unsigned __int64) * 8 - (index + 1);\n"
"#elif _M_IX86\n"
"  int result = I32_CLZ(HighDword(mask));\n"
"  if (result == 32)\n"
"    result += I32_CLZ(LowDword(mask));\n"
"  return result;\n"
"#else\n"
"#error unexpected architecture\n"
"#endif\n"
"}\n"
"\n"
"static inline int I32_CTZ(unsigned long mask) {\n"
"  if (mask == 0) return 32;\n"
"  unsigned long index;\n"
"  _BitScanForward(&index, mask);\n"
"  return index;\n"
"}\n"
"\n"
"static inline int I64_CTZ(unsigned __int64 mask) {\n"
"#if _M_X64\n"
"  if (mask == 0) return 64;\n"
"  unsigned long index;\n"
"  _BitScanForward64(&index, mask);\n"
"  return index;\n"
"#elif _M_IX86\n"
"  int result = I32_CTZ(LowDword(mask));\n"
"  if (result == 32)\n"
"    result += I32_CTZ(HighDword(mask));\n"
"  return result;\n"
"#else\n"
"#error unexpected architecture\n"
"#endif\n"
"}\n"
"\n"
"static inline int I32_POPCNT(unsigned long value) {\n"
"  return __popcnt(value);\n"
"}\n"
"\n"
"static inline int I64_POPCNT(unsigned __int64 value) {\n"
"#if _M_X64\n"
"  return __popcnt64(value);\n"
"#elif _M_IX86\n"
"  return I32_POPCNT(HighDword(value)) + I32_POPCNT(LowDword(value));\n"
"#else\n"
"#error unexpected architecture\n"
"#endif\n"
"}\n"
"\n"
"#else\n"
"#define I32_CLZ(x) ((x) ? __builtin_clz(x) : 32)\n"
"#define I64_CLZ(x) ((x) ? __builtin_clzll(x) : 64)\n"
"#define I32_CTZ(x) ((x) ? __builtin_ctz(x) : 32)\n"
"#define I64_CTZ(x) ((x) ? __builtin_ctzll(x) : 64)\n"
"#define I32_POPCNT(x) (__builtin_popcount(x))\n"
"#define I64_POPCNT(x) (__builtin_popcountll(x))\n"
"#endif\n"
"\n"
"#define DIV_S(ut, min, x, y)                                 \\\n"
"   ((UNLIKELY((y) == 0)) ?                TRAP(DIV_BY_ZERO)  \\\n"
"  : (UNLIKELY((x) == min && (y) == -1)) ? TRAP(INT_OVERFLOW) \\\n"
"  : (ut)((x) / (y)))\n"
"\n"
"#define REM_S(ut, min, x, y)                                \\\n"
"   ((UNLIKELY((y) == 0)) ?                TRAP(DIV_BY_ZERO) \\\n"
"  : (UNLIKELY((x) == min && (y) == -1)) ? 0                 \\\n"
"  : (ut)((x) % (y)))\n"
"\n"
"#define I32_DIV_S(x, y) DIV_S(u32, INT32_MIN, (s32)x, (s32)y)\n"
"#define I64_DIV_S(x, y) DIV_S(u64, INT64_MIN, (s64)x, (s64)y)\n"
"#define I32_REM_S(x, y) REM_S(u32, INT32_MIN, (s32)x, (s32)y)\n"
"#define I64_REM_S(x, y) REM_S(u64, INT64_MIN, (s64)x, (s64)y)\n"
"\n"
"#define DIVREM_U(op, x, y) \\\n"
"  ((UNLIKELY((y) == 0)) ? TRAP(DIV_BY_ZERO) : ((x) op (y)))\n"
"\n"
"#define DIV_U(x, y) DIVREM_U(/, x, y)\n"
"#define REM_U(x, y) DIVREM_U(%, x, y)\n"
"\n"
"#define ROTL(x, y, mask) \\\n"
"  (((x) << ((y) & (mask))) | ((x) >> (((mask) - (y) + 1) & (mask))))\n"
"#define ROTR(x, y, mask) \\\n"
"  (((x) >> ((y) & (mask))) | ((x) << (((mask) - (y) + 1) & (mask))))\n"
"\n"
"#define I32_ROTL(x, y) ROTL(x, y, 31)\n"
"#define I64_ROTL(x, y) ROTL(x, y, 63)\n"
"#define I32_ROTR(x, y) ROTR(x, y, 31)\n"
"#define I64_ROTR(x, y) ROTR(x, y, 63)\n"
"\n"
"#define FMIN(x, y)                                          \\\n"
"   ((UNLIKELY((x) != (x))) ? NAN                            \\\n"
"  : (UNLIKELY((y) != (y))) ? NAN                            \\\n"
"  : (UNLIKELY((x) == 0 && (y) == 0)) ? (signbit(x) ? x : y) \\\n"
"  : (x < y) ? x : y)\n"
"\n"
"#define FMAX(x, y)                                          \\\n"
"   ((UNLIKELY((x) != (x))) ? NAN                            \\\n"
"  : (UNLIKELY((y) != (y))) ? NAN                            \\\n"
"  : (UNLIKELY((x) == 0 && (y) == 0)) ? (signbit(x) ? y : x) \\\n"
"  : (x > y) ? x : y)\n"
"\n"
"#define TRUNC_S(ut, st, ft, min, max, maxop, x)                             \\\n"
"   ((UNLIKELY((x) != (x))) ? TRAP(INVALID_CONVERSION)                       \\\n"
"  : (UNLIKELY((x) < (ft)(min) || (x) maxop (ft)(max))) ? TRAP(INT_OVERFLOW) \\\n"
"  : (ut)(st)(x))\n"
"\n"
"#define I32_TRUNC_S_F32(x) TRUNC_S(u32, s32, f32, INT32_MIN, INT32_MAX, >=, x)\n"
"#define I64_TRUNC_S_F32(x) TRUNC_S(u64, s64, f32, INT64_MIN, INT64_MAX, >=, x)\n"
"#define I32_TRUNC_S_F64(x) TRUNC_S(u32, s32, f64, INT32_MIN, INT32_MAX, >,  x)\n"
"#define I64_TRUNC_S_F64(x) TRUNC_S(u64, s64, f64, INT64_MIN, INT64_MAX, >=, x)\n"
"\n"
"#define TRUNC_U(ut, ft, max, maxop, x)                                    \\\n"
"   ((UNLIKELY((x) != (x))) ? TRAP(INVALID_CONVERSION)                     \\\n"
"  : (UNLIKELY((x) <= (ft)-1 || (x) maxop (ft)(max))) ? TRAP(INT_OVERFLOW) \\\n"
"  : (ut)(x))\n"
"\n"
"#define I32_TRUNC_U_F32(x) TRUNC_U(u32, f32, UINT32_MAX, >=, x)\n"
"#define I64_TRUNC_U_F32(x) TRUNC_U(u64, f32, UINT64_MAX, >=, x)\n"
"#define I32_TRUNC_U_F64(x) TRUNC_U(u32, f64, UINT32_MAX, >,  x)\n"
"#define I64_TRUNC_U_F64(x) TRUNC_U(u64, f64, UINT64_MAX, >=, x)\n"
"\n"
"#define DEFINE_REINTERPRET(name, t1, t2)   \\\n"
"  static inline t2 WASM_RT_CC name(t1 x) { \\\n"
"    t2 result;                             \\\n"
"    memcpy(&result, &x, sizeof(result));   \\\n"
"    return result;                         \\\n"
"  }\n"
"\n"
"DEFINE_REINTERPRET(f32_reinterpret_i32, u32, f32)\n"
"DEFINE_REINTERPRET(i32_reinterpret_f32, f32, u32)\n"
"DEFINE_REINTERPRET(f64_reinterpret_i64, u64, f64)\n"
"DEFINE_REINTERPRET(i64_reinterpret_f64, f64, u64)\n"
"\n"
"#if _MSC_VER\n"
"static inline f32 __vectorcall F32_COPYSIGN(f32 x, f32 y) {\n"
"#if _M_X64 || _M_IX86\n"
"  return _mm_cvtss_f32(_mm_or_ps(\n"
"      _mm_and_ps(_mm_set_ss(x),\n"
"                 _mm_castsi128_ps(_mm_set_epi32(0, 0, 0, 0x7fffffffu))),\n"
"      _mm_and_ps(_mm_set_ss(y),\n"
"                 _mm_castsi128_ps(_mm_set_epi32(0, 0, 0, 0x80000000u)))));\n"
"#else\n"
"#error unexpected architecture\n"
"#endif\n"
"}\n"
"\n"
"static inline f64 __vectorcall F64_COPYSIGN(f64 x, f64 y) {\n"
"#if _M_X64 || _M_IX86\n"
"  return _mm_cvtsd_f64(_mm_or_pd(\n"
"      _mm_and_pd(_mm_set_sd(x), _mm_castsi128_pd(_mm_set_epi32(\n"
"                                    0, 0, 0x7fffffffu, 0xffffffffu))),\n"
"      _mm_and_pd(_mm_set_sd(y),\n"
"                 _mm_castsi128_pd(_mm_set_epi32(0, 0, 0x80000000u, 0)))));\n"
"#else\n"
"#error unexpected architecture\n"
"#endif\n"
"}\n"
"\n"
"static inline f32 __vectorcall F32_ABS(f32 x) { return F32_COPYSIGN(x, 0.f); }\n"
"static inline f64 __vectorcall F64_ABS(f64 x) { return F64_COPYSIGN(x, 0.f); }\n"
"#else\n"
"#define F32_ABS fabsf\n"
"#define F64_ABS fabs\n"
"#define F32_COPYSIGN copysignf\n"
"#define F64_COPYSIGN copysign\n"
"#endif\n"
"\n"
;
