/* Automatically generated by wasm2c */
#ifndef FAC_H_GENERATED_
#define FAC_H_GENERATED_

#include "wasm-rt.h"

#if defined(WASM_RT_ENABLE_EXCEPTION_HANDLING)
#include "wasm-rt-exceptions.h"
#endif

#if defined(WASM_RT_ENABLE_SIMD)
#include "simde/wasm/simd128.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif

typedef struct w2c_fac {
  char dummy_member;
} w2c_fac;

void wasm2c_fac_instantiate(w2c_fac*);
void wasm2c_fac_free(w2c_fac*);
wasm_rt_func_type_t wasm2c_fac_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* export: 'fac' */
uint32_t w2c_fac_fac(w2c_fac*, uint32_t);

#ifdef __cplusplus
}
#endif

#endif  /* FAC_H_GENERATED_ */
